version: '3.8'

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    container_name: my-frontend
    ports:
      - "8000:8000"
    depends_on:
      - back
  back:
    image: node:16
    container_name: my-backend
    working_dir: /app
    command: [ "node", "index.js" ]
    ports:
      - "4000:4000"
    volumes:
      - ./back:/app
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      BACKEND_PORT: 4000
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: ahrtemis-postgres
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui_1
    ports:
      - "3001:8080"
    volumes:
      - ./swagger/openapi.json:/openapi.json
    environment:
      SWAGGER_JSON: /openapi.json

volumes:
  postgres_data:
